image:
  repo: gcarrarom/landing
  tag: 0.0.0
  pullSecrets: []

port: 80

env: []

domain: fancywhale.ca
## Set the url value if you want to replace the entire hostname
# url: something.fancywhale.ca
clusterissuer: letsencrypt

ingress:
  annotations: {}