image:
  repo: gcarrarom/landing
  tag: 0.0.0
  pullSecrets: []

port: 80

recreate: false
env: []

# Volumes to be mounted from PVCs like this:
# - name: vault-pvc # name of the PVC to be mounted
#   path: /data # path where the pvc will be mounted at
volumes: []

# Environment Variables from Secrets, can be set like this:
# - name: "ENV_VAR" #name of the environment variable
#   secretName: super-secret # Name of the kubernetes secret
#   key: password # key of the secret to be used.
#   secretRef: false # Whether to use it as a secret ref or not (uses all keys as environment variables)
envFromSecret: []

domain: fancywhale.ca
## Set the url value if you want to replace the entire hostname
# url: something.fancywhale.ca
clusterissuer: letsencrypt

ingress:
  annotations: {}