image:
  repo: gcarrarom/landing
  tag: 0.0.0
  pullSecrets: []

port: 80

## Name to be used on the resources created
# Defaults to .Release.Name
# name: 

deployment:
  enabled: true

recreate: false
env: {}

# Volumes to be mounted from PVCs like this: - defaults to pvc if isNfs = false
# - name: vault-pvc # name of the PVC or secret to be mounted.
#   path: /data # path where the pvc will be mounted at
#   isSecret: false # Whether or not to use the name to attach the secret with the same name.
#   isNfs: true # wheter to connect using nfs or not
#   nfsPath: /data # path to mount at for the NFS server
#   server: some.server.com # nfs server
#   createPVC: false # Whether or not to create a PVC
#   storageClassName: nfs-client
#   size: 10G # size of the pvc to be created if createPVC = true
volumes: []

# Environment Variables from Secrets, can be set like this:
# - name: "ENV_VAR" #name of the environment variable
#   secretName: super-secret # Name of the kubernetes secret
#   key: password # key of the secret to be used.
#   secretRef: false # Whether to use it as a secret ref or not (uses all keys as environment variables)
envFromSecret: []

domain: fancywhale.ca
## Set the url value if you want to replace the entire hostname
# url: something.fancywhale.ca
clusterissuer: letsencrypt

ingress:
  className: nginx
  enabled: true
  annotations: {}
  ## Auth annotations should be the ones included for authentication only. 
  # Those will be ignored on the noauth ingress to be created
  # That will allow for endpoints without authentication.
  authAnnotations: {}
  # Paths where you don't want to use your external authentication
  # This is usually interesting to use on status/health pages and some APIs
  noauthPaths: []

service:
  enabled: true
  protocol: TCP
  # You can use ClusterIP or LoadBalancer Services
  # If you use LoadBalancer services, you could set the static IP address using:
  # loadBalancerIP: <ip address>
  # Make sure to research how that's going to be allocated.
  type: ClusterIP
  # Extra ports if you need more than 1
  # Example:
  # - port: 80
  #   protocol: UDP
  ports: []

resources:
  requests: {}
  limits: {}

###
# This is where you can define your node selector. 
# If you need to use GCP's node selector, you can use:
# gcp: <computer-class>
# Where computer class could be: "Scale-Out", "Balanced" or "General-purpose"
nodeSelector:
  gcp: false
  enabled: false
  labels: {}
  # labels: 
  #   disk: ssd

###
# This is where you can define your Security Context settings
# You can setup the fsgroup setting by using this:
# fsgroup: <group ID>
# Where you can set any group ID that you need.
securityContext:
  enabled: false

###
# Service account related values
serviceAccount:
  enabled: false