{{- $app_name := .Release.Name }}
{{- $app_port := .Values.port }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $app_name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $app_name }}
  template:
    metadata:
      labels:
        app: {{ $app_name }}
    spec:
      {{- if not (eq (len .Values.image.pullSecrets) 0) }}
      imagePullSecrets:
      {{- range $each := .Values.image.pullSecrets }}
      - name: {{ $each }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ $app_name }}
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        {{- if or (not (eq (len .Values.env) 0) (not (eq (len .Values.envFromSecret) 0)}}
        env:
        {{- range $key, $val := .Values.env }}
        - name: {{$key}}
          value: {{$val | quote}}
        {{- end }}
        {{- range $item := .Values.envFromSecret }}
        - name: {{$item.name}}
          valueFrom:
          secretKeyRef:
            name: {{$item.secretName}}
            key: {{$item.key}}
        {{- end}}
        {{- end }}
        ports:
        - containerPort: {{ $app_port }}
---
kind: Service
apiVersion: v1
metadata:
  name:  {{ $app_name }}
spec:
  selector:
    app: {{ $app_name }}
  type:  ClusterIP
  ports:
  - port:  {{ $app_port }}
    targetPort:  {{ $app_port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $app_name }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterissuer }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote}}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
  - host: {{ if .Values.url }}{{ .Values.url }}{{ else }}{{ $app_name }}.{{ .Values.domain }}{{ end }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ $app_name }}
            port:
              number: {{ $app_port }}
  tls:
  - hosts:
    - {{ if .Values.url }}{{ .Values.url }}{{ else }}{{ $app_name }}.{{ .Values.domain }}{{ end }}
    secretName: {{ if .Values.url }}{{ .Values.url | replace "." "-" }}{{ else }}{{ $app_name }}-{{ .Values.domain | replace "." "-" }}{{ end }}