{{- $serviceAccountName := default .Release.Name .Values.name }}
{{- if .Values.serviceAccount.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{$serviceAccountName}}
{{- end}}
{{- if .Values.serviceAccount.role }}
{{- $roleName := default $serviceAccountName .Values.serviceAccount.role.name }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{$roleName}}
rules:
{{ .Values.serviceAccount.role.rules | toYaml }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{$serviceAccountName}}
subjects:
- kind: ServiceAccount
  name: {{$serviceAccountName}}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{$roleName}}
  apiGroup: rbac.authorization.k8s.io 
{{- end -}}